config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to:  'static_pages#help' 
  get  '/about',   to:  'static_pages#about'
  get  '/contact', to:  'static_pages#contact'
  
  get  '/signup',  to:  'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :talks#talk一覧
    end

    collection do #user検索用
      get :search
    end
  end

  

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :replies,             only: [:create, :destroy]
  
  resources :talks,               only: [:show, :create]
  #talk詳細　message一覧
  
  resources :messages,            only: [:create]
  #message_form
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts, dependent: :destroy
    # default: class_name: "Micropst"
    # default: foreign_key: "User_id"
    # default  #{Model Name}s"
    has_many :active_relationships,  class_name: "Relationship",
                                    foreign_key: "follower_id",
                                      dependent: :destroy

    has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                      dependent: :destroy

    has_many :following,                through: :active_relationships, 
                                         source: :followed

    has_many :followers,                through: :passive_relationships,
                                         source: :follower

    has_many :messages,               dependent: :destroy

    has_many :memberships,            dependent: :destroy

    has_many :talks,                    through: :memberships,
                                         source: :talk,
                                      dependent: :destroy
    #user.talksでuserの参加しているtalkを表示する
    #userのuser_idを参照してmembershipを取り出し、そのmembershipからtalk_idを参照してtalkを取り出す
    attr_accessor :remember_token, 
                  :activation_token,
                  :reset_token
    before_save   :downcase_email
    before_create :create_activation_digest
    validates :name,  presence: true, 
                      length: { maximum: 50 },
                      uniqueness: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true

    has_secure_password
    validates :password, presence: true, 
                         length: { minimum: 6 },
                         allow_nil: true

     # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end  
    
    # ランダムなトークンを返す
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # 永続セッションのためにユーザーをデータベースに記憶する
    #コンピューター間の処理なのでvaridationに引っ掛かることがない
    #varidationをスキップして処理をはやめる
    #update_attributeはvaridationをスキップして、データベースを更新する
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # 渡されたトークンがダイジェストと一致したらtrueを返す
    # attribute: reemeber, activation, reset
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    # ユーザーのログイン情報を破棄する
    def forget
        self.update_attribute(:remember_digest, nil)
    end

    # アカウントを有効にする
    def activate
        update_columns(activated: true, activated_at: Time.zone.now)
    end

     # 有効化用のメールを送信する
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    # パスワード再設定の属性を設定する
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest,  User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
        update_columns(reset_digest: User.digest(reset_token),
                       reset_sent_at: Time.zone.now)
    end

    # パスワード再設定のメールを送信する
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    # パスワード再設定の期限が切れている場合はtrueを返す
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    # 試作feedの定義
    # 完全な実装は次章の「ユーザーをフォローする」を参照
    def feed
        #Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
        #self.idを省略=> id
        following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
        # 返信用micropostをfeedに含める
        reply_ids = "SELECT micropost_id FROM replies WHERE in_reply_to = :user_id"
        Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id OR id IN (#{reply_ids})", user_id: id)
    end

    # ユーザーをフォローする
    def follow(other_user)
        following << other_user
    end

    # ユーザーをフォロー解除する
    def unfollow(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end

    # 現在のユーザーがフォローしてたらtrueを返す
    def following?(other_user)
        following.include?(other_user)
    end

    #新しくフォロワーが増えたときの通知メールを送信
    def send_more_followers_email(follower)
        UserMailer.more_followers(self, follower).deliver_now
    end

    private
        # メールアドレスをすべて小文字にする
        def downcase_email
        self.email.downcase!
        end

        # 有効化トークンとダイジェストを作成および代入する
        def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers, :talks, :search]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy


  #GET /users
  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    if params[:search]
      @microposts = @user.microposts.where("content LIKE ?", 
      "%#{params[:search][:content]}%").paginate(page: params[:page])
    else
      @microposts = @user.microposts.paginate(page: params[:page])  
    end
    redirect_to root_url and return unless @user.activated?
    @talk = Talk.new
  end
  
  # GET /users/new
  def new
    @user = User.new
  end
  
  # POST /users (+ params)
  def create
    @user = User.create(user_params)
    #チェックボックスによって通知のオンオフを切り替える
    params[:user][:follow_notify] == "1" ? @user.follow_notify = true : @user.follow_notify = false
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  # GET  /users/:id/edit
  def edit
    @user = User.find(params[:id])
    # => app/views/users/edit.html.erb
  end


  #PATCH /users/
  def update
    @user = User.find(params[:id])
    #チェックボックスによって通知のオンオフを切り替える
    params[:user][:follow_notify] == "1" ? @user.follow_notify = true : @user.follow_notify = false
    if @user.update(user_params)
      # 更新に成功した場合を扱う。
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  #DELETE /user/:id
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url, status: :see_other
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def talks
    @talks = current_user.talks.paginate(page: params[:page])
  end

  def search
    #indexにrenderされた時のために@usersを定義
    @users = User.where(activated: true).paginate(page: params[:page])
    if search_params[:name] #nameで検索された場合
      if search_params[:name].blank? #空白が入力されたらユーザー一覧に戻す
        render 'index'
      else      
        @searched_users = User.where("name LIKE ?",
              "%#{search_params[:name]}%").paginate(page: params[:page])
      end
    elsif search_params[:id] #idで検索された場合
      if search_params[:id].blank? #空白が入力されたらユーザー一覧に戻る
        render 'index'
      else
        @searched_users = User.where(id: search_params[:id]
                          ).paginate(page: params[:page])
      end
    end
  end


  private
      def user_params
        params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation,)
      end

      def search_params
        params.require(:search).permit(:name, :id)
      end

      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end

      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
      
end

app/helpers/users_helper.rb
module UsersHelper
    # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80})
    size        =options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
  
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.label :follow_notify, class: "checkbox inline" do %>
        <%= f.check_box :follow_notify %>
        <span>Enable follow nitify</span>
    <% end %>
  
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    
<% end %>

app/views/users/_searched_user.html.erb
<li>
    <%= gravatar_for searched_user, size: 50 %>
    <%= link_to searched_user.name, searched_user %>
    
</li>

<%# user_path(user) => userに省略%>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user,
                data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <% end %>
</li>

<%# user_path(user) => userに省略%>

app/views/users/_user_search_form.html.erb
<h4 class="search_way">search for name</h4>
<%= form_with(url: search_users_path, scope: :search, #params[:search]に保存
                                        method: :get, #searchアクションを指定
                                        local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.submit "search user", class: "btn btn-primary" %>

<% end %>

<h4 class="search_way">search for id</h4>
<%= form_with(url: search_users_path, scope: :search, #params[:search]に保存
                                        method: :get, #searchアクションを指定
                                        local: true) do |f| %>
    <%= f.label :id %>
    <%= f.number_field :id, class: 'form-control' %>

    <%= f.submit "search user", class: "btn btn-primary" %>

<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank" rel = "noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<h3 class="search_user">Search user</h3>
<%= render 'users/user_search_form' %>

<%= will_paginate %>

<ul class="users">

  <%= render @users %>

  <%# デフォルトで以下のコードを呼び出すパーシャルになっている　%>
  <%# @users.each do |user| %>
    <%#= render user %>
  <%# end %>

</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= render 'form' %>
  </div>
</div>

app/views/users/search.html.erb
<%= provide(:title, "Searched Users") %>
<h1>Searched users</h1>

<ul class="users">
    <% if @searched_users.blank? %>
        <h2>User not found</h2>
    <% else %>
        <% @searched_users.each do |searched_user| %>
            <li>
                <%= gravatar_for searched_user, size: 50 %>
                <%= link_to searched_user.name, searched_user %>
            </li>
        <% end %>
    <% end %>
</ul>
<%= will_paginate @searched_users %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
    <div class="row">
      <aside class="col-xs-4">
        <section class="user_info">
          <h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
          </h1>
            
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
            <% if @user != current_user %>
              <%= form_with(model: @talk, remote: true) do |f| %>
                <div><%= hidden_field_tag :user_id, @user.id %></div>
                <%= f.submit "Message", class: "btn btn-primary" %>
              <% end %>
            <% end %>
        <section class="search">
            <h1>search micropost</h1>
            <%= form_with(url: user_path(@user), scope: :search,
                                      method: :get,
                                      local: true) do |f| %>
              <%= f.label :content %>
              <%= f.text_field :content, class: 'form-control' %>
          
              <%= f.submit "search micropost", class: "btn btn-primary" %>
            <% end %>
        </section>
      </aside>
      <div class="col-xs-8">
        <%= render 'follow_form' if logged_in? %>
        <% if @user.microposts.any? %>
          <h3>Microposts (<%= @user.microposts.count %>)</h3>
          <ol class="microposts">
            <% if params[:search] %>
              <h4>search result</h4>
            <% end %>
            <%= render @microposts %>
          </ol>
          <%= will_paginate @microposts %>
        <% end %>
      </div>
    </div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/talks.html.erb
<%= provide(:title, 'messages') %>
<div class="row">
    <aside class="col-xs-4">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
            <%= render 'shared/stats' %>
        </section>
    </aside>
    <div class="col-xs-8">
        <h1>All messages</h1>
        <div class="talks">
            <%= render @talks %>
        </div>
        <%= will_paginate @talks %>
    </div>
    
</div>